import React, { useState, useEffect } from "react";
import { useParams } from "react-router-dom";
import useFetch from "../hooks/useFetch";
import useFormattedPage from "../hooks/useFormattedPage";

export default function Surah() {
  // let { id } = useParams();
  let res = {
    data: [
      {
        id: 6,
        pageNumber: 6,
        chapterCode: "002",
        hizbNumber: 1,
        juzNumber: 1,
        rubNumber: 2,
        lines: [
          {
            id: 62,
            pageID: 6,
            words: [
              {
                id: 32691,
                color: "black",
                text: "ﭑ",
                lineID: 62,
                lineNumber: 1,
                audioUrl: "wbw/002_030_001.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 32692,
                color: "black",
                text: "ﭒ",
                lineID: 62,
                lineNumber: 1,
                audioUrl: "wbw/002_030_002.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 32693,
                color: "black",
                text: "ﭓ",
                lineID: 62,
                lineNumber: 1,
                audioUrl: "wbw/002_030_003.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 32694,
                color: "black",
                text: "ﭔ",
                lineID: 62,
                lineNumber: 1,
                audioUrl: "wbw/002_030_004.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 32695,
                color: "black",
                text: "ﭕ",
                lineID: 62,
                lineNumber: 1,
                audioUrl: "wbw/002_030_005.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 32696,
                color: "black",
                text: "ﭖ",
                lineID: 62,
                lineNumber: 1,
                audioUrl: "wbw/002_030_006.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 32697,
                color: "black",
                text: "ﭗ",
                lineID: 62,
                lineNumber: 1,
                audioUrl: "wbw/002_030_007.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 32698,
                color: "black",
                text: "ﭘ",
                lineID: 62,
                lineNumber: 1,
                audioUrl: "wbw/002_030_008.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 32699,
                color: "black",
                text: "ﭙﭚ",
                lineID: 62,
                lineNumber: 1,
                audioUrl: "wbw/002_030_009.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
            ],
          },
          {
            id: 63,
            pageID: 6,
            words: [
              {
                id: 32701,
                color: "black",
                text: "ﭛ",
                lineID: 63,
                lineNumber: 2,
                audioUrl: "wbw/002_030_011.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 32702,
                color: "black",
                text: "ﭜ",
                lineID: 63,
                lineNumber: 2,
                audioUrl: "wbw/002_030_012.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 32703,
                color: "black",
                text: "ﭝ",
                lineID: 63,
                lineNumber: 2,
                audioUrl: "wbw/002_030_013.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 32704,
                color: "black",
                text: "ﭞ",
                lineID: 63,
                lineNumber: 2,
                audioUrl: "wbw/002_030_014.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 32705,
                color: "black",
                text: "ﭟ",
                lineID: 63,
                lineNumber: 2,
                audioUrl: "wbw/002_030_015.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 32706,
                color: "black",
                text: "ﭠ",
                lineID: 63,
                lineNumber: 2,
                audioUrl: "wbw/002_030_016.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 32707,
                color: "black",
                text: "ﭡ",
                lineID: 63,
                lineNumber: 2,
                audioUrl: "wbw/002_030_017.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 32708,
                color: "black",
                text: "ﭢ",
                lineID: 63,
                lineNumber: 2,
                audioUrl: "wbw/002_030_018.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 32709,
                color: "black",
                text: "ﭣ",
                lineID: 63,
                lineNumber: 2,
                audioUrl: "wbw/002_030_019.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
            ],
          },
          {
            id: 64,
            pageID: 6,
            words: [
              {
                id: 32710,
                color: "black",
                text: "ﭤ",
                lineID: 64,
                lineNumber: 3,
                audioUrl: "wbw/002_030_020.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 32711,
                color: "black",
                text: "ﭥ",
                lineID: 64,
                lineNumber: 3,
                audioUrl: "wbw/002_030_021.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 32712,
                color: "black",
                text: "ﭦ",
                lineID: 64,
                lineNumber: 3,
                audioUrl: "wbw/002_030_022.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 32713,
                color: "black",
                text: "ﭧﭨ",
                lineID: 64,
                lineNumber: 3,
                audioUrl: "wbw/002_030_023.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 32715,
                color: "black",
                text: "ﭩ",
                lineID: 64,
                lineNumber: 3,
                audioUrl: "wbw/002_030_025.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 32716,
                color: "black",
                text: "ﭪ",
                lineID: 64,
                lineNumber: 3,
                audioUrl: "wbw/002_030_026.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 32717,
                color: "black",
                text: "ﭫ",
                lineID: 64,
                lineNumber: 3,
                audioUrl: "wbw/002_030_027.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 32718,
                color: "black",
                text: "ﭬ",
                lineID: 64,
                lineNumber: 3,
                audioUrl: "wbw/002_030_028.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 32719,
                color: "black",
                text: "ﭭ",
                lineID: 64,
                lineNumber: 3,
                audioUrl: "wbw/002_030_029.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 32720,
                color: "black",
                text: "ﭮ",
                lineID: 64,
                lineNumber: 3,
                audioUrl: "wbw/002_030_030.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
            ],
          },
          {
            id: 65,
            pageID: 6,
            words: [
              {
                id: 32721,
                color: "black",
                text: "ﭯ",
                lineID: 65,
                lineNumber: 4,
                audioUrl: null,
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 33595,
                color: "black",
                text: "ﭰ",
                lineID: 65,
                lineNumber: 4,
                audioUrl: "wbw/002_031_001.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 33596,
                color: "black",
                text: "ﭱ",
                lineID: 65,
                lineNumber: 4,
                audioUrl: "wbw/002_031_002.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 33597,
                color: "black",
                text: "ﭲ",
                lineID: 65,
                lineNumber: 4,
                audioUrl: "wbw/002_031_003.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 33598,
                color: "black",
                text: "ﭳ",
                lineID: 65,
                lineNumber: 4,
                audioUrl: "wbw/002_031_004.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 33599,
                color: "black",
                text: "ﭴ",
                lineID: 65,
                lineNumber: 4,
                audioUrl: "wbw/002_031_005.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 33600,
                color: "black",
                text: "ﭵ",
                lineID: 65,
                lineNumber: 4,
                audioUrl: "wbw/002_031_006.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 33601,
                color: "black",
                text: "ﭶ",
                lineID: 65,
                lineNumber: 4,
                audioUrl: "wbw/002_031_007.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 33602,
                color: "black",
                text: "ﭷ",
                lineID: 65,
                lineNumber: 4,
                audioUrl: "wbw/002_031_008.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
            ],
          },
          {
            id: 66,
            pageID: 6,
            words: [
              {
                id: 33603,
                color: "black",
                text: "ﭸ",
                lineID: 66,
                lineNumber: 5,
                audioUrl: "wbw/002_031_009.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 33604,
                color: "black",
                text: "ﭹ",
                lineID: 66,
                lineNumber: 5,
                audioUrl: "wbw/002_031_010.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 33605,
                color: "black",
                text: "ﭺ",
                lineID: 66,
                lineNumber: 5,
                audioUrl: "wbw/002_031_011.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 33606,
                color: "black",
                text: "ﭻ",
                lineID: 66,
                lineNumber: 5,
                audioUrl: "wbw/002_031_012.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 33607,
                color: "black",
                text: "ﭼ",
                lineID: 66,
                lineNumber: 5,
                audioUrl: "wbw/002_031_013.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 33608,
                color: "black",
                text: "ﭽ",
                lineID: 66,
                lineNumber: 5,
                audioUrl: "wbw/002_031_014.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 33609,
                color: "black",
                text: "ﭾ",
                lineID: 66,
                lineNumber: 5,
                audioUrl: "wbw/002_031_015.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 33610,
                color: "black",
                text: "ﭿ",
                lineID: 66,
                lineNumber: 5,
                audioUrl: null,
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 34673,
                color: "black",
                text: "ﮀ",
                lineID: 66,
                lineNumber: 5,
                audioUrl: "wbw/002_032_001.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
            ],
          },
          {
            id: 67,
            pageID: 6,
            words: [
              {
                id: 34674,
                color: "black",
                text: "ﮁ",
                lineID: 67,
                lineNumber: 6,
                audioUrl: "wbw/002_032_002.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 34675,
                color: "black",
                text: "ﮂ",
                lineID: 67,
                lineNumber: 6,
                audioUrl: "wbw/002_032_003.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 34676,
                color: "black",
                text: "ﮃ",
                lineID: 67,
                lineNumber: 6,
                audioUrl: "wbw/002_032_004.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 34677,
                color: "black",
                text: "ﮄ",
                lineID: 67,
                lineNumber: 6,
                audioUrl: "wbw/002_032_005.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 34678,
                color: "black",
                text: "ﮅ",
                lineID: 67,
                lineNumber: 6,
                audioUrl: "wbw/002_032_006.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 34679,
                color: "black",
                text: "ﮆ",
                lineID: 67,
                lineNumber: 6,
                audioUrl: "wbw/002_032_007.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 34680,
                color: "black",
                text: "ﮇﮈ",
                lineID: 67,
                lineNumber: 6,
                audioUrl: "wbw/002_032_008.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 34682,
                color: "black",
                text: "ﮉ",
                lineID: 67,
                lineNumber: 6,
                audioUrl: "wbw/002_032_010.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 34683,
                color: "black",
                text: "ﮊ",
                lineID: 67,
                lineNumber: 6,
                audioUrl: "wbw/002_032_011.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 34684,
                color: "black",
                text: "ﮋ",
                lineID: 67,
                lineNumber: 6,
                audioUrl: "wbw/002_032_012.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 34685,
                color: "black",
                text: "ﮌ",
                lineID: 67,
                lineNumber: 6,
                audioUrl: "wbw/002_032_013.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
            ],
          },
          {
            id: 68,
            pageID: 6,
            words: [
              {
                id: 34686,
                color: "black",
                text: "ﮍ",
                lineID: 68,
                lineNumber: 7,
                audioUrl: null,
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 35503,
                color: "black",
                text: "ﮎ",
                lineID: 68,
                lineNumber: 7,
                audioUrl: "wbw/002_033_001.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 35504,
                color: "black",
                text: "ﮏ",
                lineID: 68,
                lineNumber: 7,
                audioUrl: "wbw/002_033_002.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 35505,
                color: "black",
                text: "ﮐ",
                lineID: 68,
                lineNumber: 7,
                audioUrl: "wbw/002_033_003.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 35506,
                color: "black",
                text: "ﮑﮒ",
                lineID: 68,
                lineNumber: 7,
                audioUrl: "wbw/002_033_004.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 35508,
                color: "black",
                text: "ﮓ",
                lineID: 68,
                lineNumber: 7,
                audioUrl: "wbw/002_033_006.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 35509,
                color: "black",
                text: "ﮔ",
                lineID: 68,
                lineNumber: 7,
                audioUrl: "wbw/002_033_007.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 35510,
                color: "black",
                text: "ﮕ",
                lineID: 68,
                lineNumber: 7,
                audioUrl: "wbw/002_033_008.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 35511,
                color: "black",
                text: "ﮖ",
                lineID: 68,
                lineNumber: 7,
                audioUrl: "wbw/002_033_009.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
            ],
          },
          {
            id: 69,
            pageID: 6,
            words: [
              {
                id: 35512,
                color: "black",
                text: "ﮗ",
                lineID: 69,
                lineNumber: 8,
                audioUrl: "wbw/002_033_010.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 35513,
                color: "black",
                text: "ﮘ",
                lineID: 69,
                lineNumber: 8,
                audioUrl: "wbw/002_033_011.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 35514,
                color: "black",
                text: "ﮙ",
                lineID: 69,
                lineNumber: 8,
                audioUrl: "wbw/002_033_012.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 35515,
                color: "black",
                text: "ﮚ",
                lineID: 69,
                lineNumber: 8,
                audioUrl: "wbw/002_033_013.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 35516,
                color: "black",
                text: "ﮛ",
                lineID: 69,
                lineNumber: 8,
                audioUrl: "wbw/002_033_014.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 35517,
                color: "black",
                text: "ﮜ",
                lineID: 69,
                lineNumber: 8,
                audioUrl: "wbw/002_033_015.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 35518,
                color: "black",
                text: "ﮝ",
                lineID: 69,
                lineNumber: 8,
                audioUrl: "wbw/002_033_016.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 35519,
                color: "black",
                text: "ﮞ",
                lineID: 69,
                lineNumber: 8,
                audioUrl: "wbw/002_033_017.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 35520,
                color: "black",
                text: "ﮟ",
                lineID: 69,
                lineNumber: 8,
                audioUrl: "wbw/002_033_018.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 35521,
                color: "black",
                text: "ﮠ",
                lineID: 69,
                lineNumber: 8,
                audioUrl: "wbw/002_033_019.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
            ],
          },
          {
            id: 70,
            pageID: 6,
            words: [
              {
                id: 35522,
                color: "black",
                text: "ﮡ",
                lineID: 70,
                lineNumber: 9,
                audioUrl: "wbw/002_033_020.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 35523,
                color: "black",
                text: "ﮢ",
                lineID: 70,
                lineNumber: 9,
                audioUrl: "wbw/002_033_021.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 35524,
                color: "black",
                text: "ﮣ",
                lineID: 70,
                lineNumber: 9,
                audioUrl: "wbw/002_033_022.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 35525,
                color: "black",
                text: "ﮤ",
                lineID: 70,
                lineNumber: 9,
                audioUrl: "wbw/002_033_023.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 35526,
                color: "black",
                text: "ﮥ",
                lineID: 70,
                lineNumber: 9,
                audioUrl: null,
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 36491,
                color: "black",
                text: "ﮦ",
                lineID: 70,
                lineNumber: 9,
                audioUrl: "wbw/002_034_001.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 36492,
                color: "black",
                text: "ﮧ",
                lineID: 70,
                lineNumber: 9,
                audioUrl: "wbw/002_034_002.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 36493,
                color: "black",
                text: "ﮨ",
                lineID: 70,
                lineNumber: 9,
                audioUrl: "wbw/002_034_003.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 36494,
                color: "black",
                text: "ﮩ",
                lineID: 70,
                lineNumber: 9,
                audioUrl: "wbw/002_034_004.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
            ],
          },
          {
            id: 71,
            pageID: 6,
            words: [
              {
                id: 36495,
                color: "black",
                text: "ﮪ",
                lineID: 71,
                lineNumber: 10,
                audioUrl: "wbw/002_034_005.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 36496,
                color: "black",
                text: "ﮫ",
                lineID: 71,
                lineNumber: 10,
                audioUrl: "wbw/002_034_006.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 36497,
                color: "black",
                text: "ﮬ",
                lineID: 71,
                lineNumber: 10,
                audioUrl: "wbw/002_034_007.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 36498,
                color: "black",
                text: "ﮭ",
                lineID: 71,
                lineNumber: 10,
                audioUrl: "wbw/002_034_008.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 36499,
                color: "black",
                text: "ﮮ",
                lineID: 71,
                lineNumber: 10,
                audioUrl: "wbw/002_034_009.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 36500,
                color: "black",
                text: "ﮯ",
                lineID: 71,
                lineNumber: 10,
                audioUrl: "wbw/002_034_010.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 36501,
                color: "black",
                text: "ﮰ",
                lineID: 71,
                lineNumber: 10,
                audioUrl: "wbw/002_034_011.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 36502,
                color: "black",
                text: "ﮱ",
                lineID: 71,
                lineNumber: 10,
                audioUrl: "wbw/002_034_012.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 36503,
                color: "black",
                text: "ﯓ",
                lineID: 71,
                lineNumber: 10,
                audioUrl: "wbw/002_034_013.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
            ],
          },
          {
            id: 72,
            pageID: 6,
            words: [
              {
                id: 36504,
                color: "black",
                text: "ﯔ",
                lineID: 72,
                lineNumber: 11,
                audioUrl: null,
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 37359,
                color: "black",
                text: "ﯕ",
                lineID: 72,
                lineNumber: 11,
                audioUrl: "wbw/002_035_001.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 37360,
                color: "black",
                text: "ﯖ",
                lineID: 72,
                lineNumber: 11,
                audioUrl: "wbw/002_035_002.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 37361,
                color: "black",
                text: "ﯗ",
                lineID: 72,
                lineNumber: 11,
                audioUrl: "wbw/002_035_003.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 37362,
                color: "black",
                text: "ﯘ",
                lineID: 72,
                lineNumber: 11,
                audioUrl: "wbw/002_035_004.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 37363,
                color: "black",
                text: "ﯙ",
                lineID: 72,
                lineNumber: 11,
                audioUrl: "wbw/002_035_005.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 37364,
                color: "black",
                text: "ﯚ",
                lineID: 72,
                lineNumber: 11,
                audioUrl: "wbw/002_035_006.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 37365,
                color: "black",
                text: "ﯛ",
                lineID: 72,
                lineNumber: 11,
                audioUrl: "wbw/002_035_007.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 37366,
                color: "black",
                text: "ﯜ",
                lineID: 72,
                lineNumber: 11,
                audioUrl: "wbw/002_035_008.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 37367,
                color: "black",
                text: "ﯝ",
                lineID: 72,
                lineNumber: 11,
                audioUrl: "wbw/002_035_009.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
            ],
          },
          {
            id: 73,
            pageID: 6,
            words: [
              {
                id: 37368,
                color: "black",
                text: "ﯞ",
                lineID: 73,
                lineNumber: 12,
                audioUrl: "wbw/002_035_010.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 37369,
                color: "black",
                text: "ﯟ",
                lineID: 73,
                lineNumber: 12,
                audioUrl: "wbw/002_035_011.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 37370,
                color: "black",
                text: "ﯠ",
                lineID: 73,
                lineNumber: 12,
                audioUrl: "wbw/002_035_012.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 37371,
                color: "black",
                text: "ﯡ",
                lineID: 73,
                lineNumber: 12,
                audioUrl: "wbw/002_035_013.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 37372,
                color: "black",
                text: "ﯢ",
                lineID: 73,
                lineNumber: 12,
                audioUrl: "wbw/002_035_014.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 37373,
                color: "black",
                text: "ﯣ",
                lineID: 73,
                lineNumber: 12,
                audioUrl: "wbw/002_035_015.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 37374,
                color: "black",
                text: "ﯤ",
                lineID: 73,
                lineNumber: 12,
                audioUrl: "wbw/002_035_016.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 37375,
                color: "black",
                text: "ﯥ",
                lineID: 73,
                lineNumber: 12,
                audioUrl: "wbw/002_035_017.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 37376,
                color: "black",
                text: "ﯦ",
                lineID: 73,
                lineNumber: 12,
                audioUrl: "wbw/002_035_018.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 37377,
                color: "black",
                text: "ﯧ",
                lineID: 73,
                lineNumber: 12,
                audioUrl: null,
                chapterCode: null,
                isNewChapter: false,
              },
            ],
          },
          {
            id: 74,
            pageID: 6,
            words: [
              {
                id: 38099,
                color: "black",
                text: "ﯨ",
                lineID: 74,
                lineNumber: 13,
                audioUrl: "wbw/002_036_001.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 38100,
                color: "black",
                text: "ﯩ",
                lineID: 74,
                lineNumber: 13,
                audioUrl: "wbw/002_036_002.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 38101,
                color: "black",
                text: "ﯪ",
                lineID: 74,
                lineNumber: 13,
                audioUrl: "wbw/002_036_003.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 38102,
                color: "black",
                text: "ﯫ",
                lineID: 74,
                lineNumber: 13,
                audioUrl: "wbw/002_036_004.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 38103,
                color: "black",
                text: "ﯬ",
                lineID: 74,
                lineNumber: 13,
                audioUrl: "wbw/002_036_005.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 38104,
                color: "black",
                text: "ﯭ",
                lineID: 74,
                lineNumber: 13,
                audioUrl: "wbw/002_036_006.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 38105,
                color: "black",
                text: "ﯮﯯ",
                lineID: 74,
                lineNumber: 13,
                audioUrl: "wbw/002_036_007.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 38107,
                color: "black",
                text: "ﯰ",
                lineID: 74,
                lineNumber: 13,
                audioUrl: "wbw/002_036_009.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 38108,
                color: "black",
                text: "ﯱ",
                lineID: 74,
                lineNumber: 13,
                audioUrl: "wbw/002_036_010.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
            ],
          },
          {
            id: 75,
            pageID: 6,
            words: [
              {
                id: 38109,
                color: "black",
                text: "ﯲ",
                lineID: 75,
                lineNumber: 14,
                audioUrl: "wbw/002_036_011.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 38110,
                color: "black",
                text: "ﯳ",
                lineID: 75,
                lineNumber: 14,
                audioUrl: "wbw/002_036_012.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 38111,
                color: "black",
                text: "ﯴﯵ",
                lineID: 75,
                lineNumber: 14,
                audioUrl: "wbw/002_036_013.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 38113,
                color: "black",
                text: "ﯶ",
                lineID: 75,
                lineNumber: 14,
                audioUrl: "wbw/002_036_015.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 38114,
                color: "black",
                text: "ﯷ",
                lineID: 75,
                lineNumber: 14,
                audioUrl: "wbw/002_036_016.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 38115,
                color: "black",
                text: "ﯸ",
                lineID: 75,
                lineNumber: 14,
                audioUrl: "wbw/002_036_017.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 38116,
                color: "black",
                text: "ﯹ",
                lineID: 75,
                lineNumber: 14,
                audioUrl: "wbw/002_036_018.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 38117,
                color: "black",
                text: "ﯺ",
                lineID: 75,
                lineNumber: 14,
                audioUrl: "wbw/002_036_019.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 38118,
                color: "black",
                text: "ﯻ",
                lineID: 75,
                lineNumber: 14,
                audioUrl: "wbw/002_036_020.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 38119,
                color: "black",
                text: "ﯼ",
                lineID: 75,
                lineNumber: 14,
                audioUrl: "wbw/002_036_021.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 38120,
                color: "black",
                text: "ﯽ",
                lineID: 75,
                lineNumber: 14,
                audioUrl: null,
                chapterCode: null,
                isNewChapter: false,
              },
            ],
          },
          {
            id: 76,
            pageID: 6,
            words: [
              {
                id: 39109,
                color: "black",
                text: "ﯾ",
                lineID: 76,
                lineNumber: 15,
                audioUrl: "wbw/002_037_001.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 39110,
                color: "black",
                text: "ﯿ",
                lineID: 76,
                lineNumber: 15,
                audioUrl: "wbw/002_037_002.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 39111,
                color: "black",
                text: "ﰀ",
                lineID: 76,
                lineNumber: 15,
                audioUrl: "wbw/002_037_003.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 39112,
                color: "black",
                text: "ﰁ",
                lineID: 76,
                lineNumber: 15,
                audioUrl: "wbw/002_037_004.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 39113,
                color: "black",
                text: "ﰂ",
                lineID: 76,
                lineNumber: 15,
                audioUrl: "wbw/002_037_005.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 39114,
                color: "black",
                text: "ﰃ",
                lineID: 76,
                lineNumber: 15,
                audioUrl: "wbw/002_037_006.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 39115,
                color: "black",
                text: "ﰄﰅ",
                lineID: 76,
                lineNumber: 15,
                audioUrl: "wbw/002_037_007.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 39117,
                color: "black",
                text: "ﰆ",
                lineID: 76,
                lineNumber: 15,
                audioUrl: "wbw/002_037_009.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 39118,
                color: "black",
                text: "ﰇ",
                lineID: 76,
                lineNumber: 15,
                audioUrl: "wbw/002_037_010.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 39119,
                color: "black",
                text: "ﰈ",
                lineID: 76,
                lineNumber: 15,
                audioUrl: "wbw/002_037_011.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 39120,
                color: "black",
                text: "ﰉ",
                lineID: 76,
                lineNumber: 15,
                audioUrl: "wbw/002_037_012.mp3",
                chapterCode: null,
                isNewChapter: false,
              },
              {
                id: 39121,
                color: "black",
                text: "ﰊ",
                lineID: 76,
                lineNumber: 15,
                audioUrl: null,
                chapterCode: null,
                isNewChapter: false,
              },
            ],
          },
        ],
      },
    ],
  };
  // const data = useFetch("/api/quran/pages/6");
  let page = res?.data[0];

  return (
    <div className="PageContainer">
      <div className="surahContainer">
        {page?.lines.map((line, lineIndex) => {
          return (
            <div key={lineIndex} className="lineContainer">
              {line?.words?.map((word, wordIndex) => {
                console.log(word);
                return (
                  <div key={wordIndex} className="line">
                    {word?.chapterCode ? (
                      <div className="surahname">
                        {word.chapterCode}
                        <span>surah</span>
                      </div>
                    ) : null}
                    <span>{word?.text}</span>
                  </div>
                );
              })}
            </div>
          );
        })}
      </div>
    </div>
  );
}

/*


            <div className="lineContainer">
              {verseWords.map((word, innerIndex) => {
                let curLineNum = verseWords[innerIndex]?.line_number;
                let aftLineNum = verseWords[innerIndex + 1]?.line_number;
                let lineChange = curLineNum !== aftLineNum;
                // if (curLineNum !== befLineNum) {
                //   <br />;
                // }
                // console.log("c", curLineNum);
                // console.log("b", befLineNum);
                useEffect(() => {
                  setlinehaschanged(true);
                }, []);
                return (
                  <div className="word">
                    <span>{word.code_v1}</span>
                  </div>
                );
              })}
            </div>
          );
        })}
*/
